import React from 'react';
import {
  Utensils,
  Car,
  Home,
  Zap,
  Droplets,
  Wifi,
  Phone,
  HeartPulse,
  GraduationCap,
  Shirt,
  Gamepad2,
  Users,
  CreditCard,
  Tv,
  MoreHorizontal,
  Briefcase,
  Store,
  Award,
  Sparkles,
  ArrowDownToLine,
  ShoppingBag,
  Coffee,
  Plane,
  Fuel,
  Gift,
  Landmark,
  PiggyBank,
  Tag,
  Wallet,
  Shield,
  Stethoscope,
  Wrench,
  BookOpen,
  Film,
  Package,
  Activity,
  LucideProps
} from 'lucide-react';

export const AVAILABLE_CATEGORY_ICONS = [
  { name: 'Utensils', label: 'Alimentation / Resto', icon: Utensils },
  { name: 'Car', label: 'Transport / Auto', icon: Car },
  { name: 'Fuel', label: 'Carburant / Essence', icon: Fuel },
  { name: 'Home', label: 'Logement / Loyer', icon: Home },
  { name: 'Zap', label: 'Électricité / Énergie', icon: Zap },
  { name: 'Droplets', label: 'Eau', icon: Droplets },
  { name: 'Wifi', label: 'Internet / Connexion', icon: Wifi },
  { name: 'Phone', label: 'Téléphone / Forfait', icon: Phone },
  { name: 'HeartPulse', label: 'Santé / Soins', icon: HeartPulse },
  { name: 'Stethoscope', label: 'Médecine / Docteur', icon: Stethoscope },
  { name: 'GraduationCap', label: 'Éducation / Études', icon: GraduationCap },
  { name: 'BookOpen', label: 'Livres / Formation', icon: BookOpen },
  { name: 'Shirt', label: 'Vêtements / Mode', icon: Shirt },
  { name: 'ShoppingBag', label: 'Shopping / Achats', icon: ShoppingBag },
  { name: 'Gamepad2', label: 'Loisirs / Jeux', icon: Gamepad2 },
  { name: 'Film', label: 'Cinéma / Divertissement', icon: Film },
  { name: 'Users', label: 'Famille / Entraide', icon: Users },
  { name: 'CreditCard', label: 'Dettes / Crédit', icon: CreditCard },
  { name: 'Tv', label: 'Abonnements / TV', icon: Tv },
  { name: 'Briefcase', label: 'Salaire / Emploi', icon: Briefcase },
  { name: 'Store', label: 'Commerce / Ventes', icon: Store },
  { name: 'Award', label: 'Prime / Mérite', icon: Award },
  { name: 'Sparkles', label: 'Bonus / Gratification', icon: Sparkles },
  { name: 'ArrowDownToLine', label: 'Transfert reçu', icon: ArrowDownToLine },
  { name: 'Gift', label: 'Cadeau / Don', icon: Gift },
  { name: 'Landmark', label: 'Banque / Institution', icon: Landmark },
  { name: 'PiggyBank', label: 'Épargne / Réserve', icon: PiggyBank },
  { name: 'Wallet', label: 'Portefeuille / Cash', icon: Wallet },
  { name: 'Coffee', label: 'Café / Sorties', icon: Coffee },
  { name: 'Plane', label: 'Voyages / Billets', icon: Plane },
  { name: 'Package', label: 'Colis / Livraison', icon: Package },
  { name: 'Wrench', label: 'Entretien / Bricolage', icon: Wrench },
  { name: 'Shield', label: 'Assurance / Sécurité', icon: Shield },
  { name: 'Activity', label: 'Sport / Forme', icon: Activity },
  { name: 'Tag', label: 'Étiquette / Divers', icon: Tag },
  { name: 'MoreHorizontal', label: 'Autre / Général', icon: MoreHorizontal }
];

const ICON_MAP: Record<string, React.ComponentType<LucideProps>> = {
  Utensils,
  Car,
  Fuel,
  Home,
  Zap,
  Droplets,
  Wifi,
  Phone,
  HeartPulse,
  Stethoscope,
  GraduationCap,
  BookOpen,
  Shirt,
  ShoppingBag,
  Gamepad2,
  Film,
  Users,
  CreditCard,
  Tv,
  Briefcase,
  Store,
  Award,
  Sparkles,
  ArrowDownToLine,
  Gift,
  Landmark,
  PiggyBank,
  Wallet,
  Coffee,
  Plane,
  Package,
  Wrench,
  Shield,
  Activity,
  Tag,
  MoreHorizontal
};

interface CategoryIconProps extends LucideProps {
  name?: string;
}

export const CategoryIcon: React.FC<CategoryIconProps> = ({ name, ...props }) => {
  const IconComponent = (name && ICON_MAP[name]) ? ICON_MAP[name] : Tag;
  return <IconComponent {...props} />;
};
